### ISSUE TITLE
Increase entity render distances while zoomed in

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Up-Mods/OkZoomer#16]
It would make zooming even more useful if the render distances for things like entities and block entities were increased while zoomed in (potentially only those in view, not sure what'd be best for performance).

**Comment by RDKRACZ** [comment]
That's how optifne works right?

**Comment by supersaiyansubtlety** [comment]
I don't think it did when I used it a year or so ago, but maybe this feature's been added to optifine. 

Should be pretty easy to test: go just outside the view distance of an entity and zoom in. If it comes back into view, then it has this feature.

**Comment by EnnuiL** [comment]
I have to admit, I had initially misinterpreted this as "literally increase the render distance", which would probably be quite problematic! However? Increasing the entity render distance could be done without any real consequences (as long as Smart Occlusion is enabled!)

**Comment by EnnuiL** [comment]
This feature (configurable through the "See Distant Entities" tweak) has been implemented on The Big Update™ Part 1, to be released tomorrow;

There is, however, one minor detail: if you zoom too far into the world and look at the distant entities, you'll notice that they will be uh, glitchy! This is pretty much the Far Lands syndrome happening on a rendering level, where precision ends being lost on a far distance, and Ok Zoomer will not be able to fix the rendering system; However, I do know how this could in theory be fixed (or at least treated to eliminate the Z-fighting): we will need the [reverse Z technique](https://godotengine.org/article/introducing-reverse-z/) to be implemented on Minecraft somehow, so that a loss of precision doesn't happen on the Z axis

**Comment by EnnuiL** [comment]
Implemented on The Rebirth Update: Part 1 (v10.0.0-beta.7 and v12.0.0-beta.3, v11 pending)
